from pathlib import Path
import pandas as pd
import numpy as np

BASE = Path(__file__).resolve().parent
OUT = BASE / "outputs"

CLEAN = BASE / "archive" / "retail_clean_dataset"
CONTAMINATED = BASE / "archive" / "retail_contaminated_dataset"

# Forecast generated by D3
forecast = pd.read_csv(
    OUT / "forecast_next_8_weeks.csv"
)

# Read inventory and product data
inv = pd.read_csv(
    CLEAN / "inventory_snapshot.csv"
)

sku = pd.read_csv(
    CLEAN / "sku_master.csv"
)

flags = pd.read_csv(
    CLEAN / "sku_inventory_flags.csv"
)

# -------------------------------------------------
# 1. Aggregate 8-week forecast by SKU
# -------------------------------------------------

fc = (
    forecast
    .groupby("sku_id", as_index=False)
    .agg(
        forecast_8w_units=("prediction", "sum"),
        avg_weekly_forecast=("prediction", "mean")
    )
)

# -------------------------------------------------
# 2. Aggregate inventory by SKU
# -------------------------------------------------

iv = (
    inv
    .groupby("sku_id", as_index=False)
    .agg(
        stock_on_hand=("stock_on_hand", "sum"),
        reorder_point=("reorder_point", "sum"),
        safety_stock=("safety_stock", "sum"),
        stores=("store_id", "nunique")
    )
)

# -------------------------------------------------
# 3. Product economics
# -------------------------------------------------

prod = sku[
    [
        "sku_id",
        "sku_name",
        "category",
        "unit_price",
        "cost_price"
    ]
].copy()

# -------------------------------------------------
# 4. Combine forecast + inventory + product data
# -------------------------------------------------

r = (
    fc
    .merge(iv, on="sku_id", how="left")
    .merge(prod, on="sku_id", how="left")
)

numeric_cols = [
    "stock_on_hand",
    "reorder_point",
    "safety_stock",
    "forecast_8w_units",
    "avg_weekly_forecast",
    "unit_price",
    "cost_price"
]

for c in numeric_cols:
    r[c] = pd.to_numeric(
        r[c],
        errors="coerce"
    ).fillna(0)

# -------------------------------------------------
# 5. Risk calculations
# -------------------------------------------------

# Units that could be unavailable during the
# 8-week planning horizon
r["stockout_gap_units"] = (
    r["forecast_8w_units"]
    - r["stock_on_hand"]
).clip(lower=0)

# Inventory exceeding forecast demand + safety stock
r["overstock_excess_units"] = (
    r["stock_on_hand"]
    - (
        r["forecast_8w_units"]
        + r["safety_stock"]
    )
).clip(lower=0)

# Stockout risk
r["stockout_high"] = (
    (r["stock_on_hand"] < r["reorder_point"])
    |
    (r["forecast_8w_units"] > r["stock_on_hand"])
)

# Overstock risk
r["overstock_high"] = (
    r["stock_on_hand"]
    >
    (
        r["forecast_8w_units"]
        + r["safety_stock"]
    )
)

# Percentage of forecast demand that exceeds
# current inventory
r["stockout_risk_pct"] = np.minimum(
    100,
    100
    * r["forecast_8w_units"]
    / np.maximum(r["stock_on_hand"], 1)
)

# Overstock ratio
r["overstock_ratio"] = (
    r["stock_on_hand"]
    /
    np.maximum(
        r["forecast_8w_units"],
        1
    )
)

# -------------------------------------------------
# 6. Recommended operational action
# -------------------------------------------------

def action(row):

    if (
        row["stockout_high"]
        and row["overstock_high"]
    ):
        return "Watch / volatile"

    if row["stockout_high"]:
        return "Reorder now"

    if row["overstock_high"]:
        return "Markdown / clear"

    return "Healthy"


r["action"] = r.apply(
    action,
    axis=1
)

# -------------------------------------------------
# 7. Monetary impact
# -------------------------------------------------

r["sales_at_risk"] = (
    r["stockout_gap_units"]
    * r["unit_price"]
)

r["capital_locked"] = (
    r["overstock_excess_units"]
    * r["cost_price"]
)

# -------------------------------------------------
# 8. Existing anomaly flags
# -------------------------------------------------

stockout_skus = set(
    flags.loc[
        flags["flag"] == "STOCKOUT_RISK",
        "sku_id"
    ]
)

slow_mover_skus = set(
    flags.loc[
        flags["flag"] == "SLOW_MOVER",
        "sku_id"
    ]
)

r["risk_flag_source"] = (
    r["sku_id"]
    .isin(stockout_skus)
    .astype(int)
)

r["slow_mover_flag"] = (
    r["sku_id"]
    .isin(slow_mover_skus)
    .astype(int)
)

# -------------------------------------------------
# 9. Priority score
# -------------------------------------------------

r["priority_value"] = (
    r["sales_at_risk"]
    +
    r["capital_locked"]
)

r = r.sort_values(
    "priority_value",
    ascending=False
)

# -------------------------------------------------
# 10. Save detailed SKU risk output
# -------------------------------------------------

r.to_csv(
    OUT / "sku_risk_scoring.csv",
    index=False
)

# -------------------------------------------------
# 11. Action summary
# -------------------------------------------------

summary = (
    r["action"]
    .value_counts()
    .rename_axis("action")
    .reset_index(name="sku_count")
)

summary.to_csv(
    OUT / "risk_action_summary.csv",
    index=False
)

# -------------------------------------------------
# 12. Business impact summary
# -------------------------------------------------

impact = pd.DataFrame(
    [
        {
            "total_sales_at_risk":
                r["sales_at_risk"].sum(),

            "total_capital_locked":
                r["capital_locked"].sum(),

            "reorder_now_skus":
                (r["action"] == "Reorder now").sum(),

            "markdown_clear_skus":
                (r["action"] == "Markdown / clear").sum(),

            "watch_skus":
                (r["action"] == "Watch / volatile").sum(),

            "healthy_skus":
                (r["action"] == "Healthy").sum(),
        }
    ]
)

impact.to_csv(
    OUT / "risk_impact_summary.csv",
    index=False
)

# -------------------------------------------------
# 13. Print results
# -------------------------------------------------

print("\nD4 RISK SCORING COMPLETE")
print("=" * 60)

print("\nACTION SUMMARY")
print(summary.to_string(index=False))

print("\nBUSINESS IMPACT")
print(
    impact.to_string(index=False)
)

print("\nTOP 10 PRIORITY SKUs")

print(
    r[
        [
            "sku_id",
            "sku_name",
            "forecast_8w_units",
            "stock_on_hand",
            "stockout_gap_units",
            "sales_at_risk",
            "capital_locked",
            "action"
        ]
    ]
    .head(10)
    .to_string(index=False)
)

print("\nOutputs created:")
print(OUT / "sku_risk_scoring.csv")
print(OUT / "risk_action_summary.csv")
print(OUT / "risk_impact_summary.csv")